### ISSUE TITLE
Why doesn't matplotlib mess up axis minimum?

### ISSUE THREAD

**Issue by gcapes** [gruel/python-novice-inflammation#10]
The 'plot scaling' exercise explains why the default axis limit prevents plotting of the final data point. So why doesn't it also prevent plotting of the first data point, if the axis limits are the same as the data limits?

**Comment by gruel** [comment]
The plot scaling exercise is wrong with the newer version of matlplotlib. Now matplotlib does not set to max an min but to 10% of max and 10% of min or something like that.

We can remove it.

**Comment by gruel** [comment]
I don't know if we cannot keep it. So we can speak about the set_xlim (the goal of the exercise) and also we can show that a library can evolve and produce different results?
