### ISSUE TITLE
Show how to start a new notebook

### ISSUE THREAD

**Issue by gcapes** [gruel/python-novice-inflammation#4]
Of course you'll be demonstrating it, but probably useful to just mention this in the set up. Maybe a screenshot?

**Comment by gruel** [comment]
No possible, there are to many ways to do it and that depends on the system. On windows, there are a gui to start it, on mac I don't know and on linux there are not. If people are using the pre-install anaconda on the windows system in the room, they will use the gui.

**Comment by gcapes** [comment]
However you start the server (command line/ GUI), you end up at the same place -- a browser is opened but you only get the server at http://localhost:8888/tree. You still need to start a new notebook, and the notes don't show how to do that.

**Comment by gruel** [comment]
I understood what you mean later, when I looked at the pull request. It is
merged. Thanks for the input.
